#!/usr/bin/env node

var 
	fs = require('fs-extra')
;

var targets = {
	dev: function() {
		css();
		copyToDist();
	}
};

run();

function run() {
	var 
		argv = process.argv,
		target
	;
	if (argv.length === 3)
		target = argv[2];
	else
		target = 'dev';
	
	try {
		console.log('Running ' + target + ' target');
		targets[target]();
	}
	catch(e) {
		console.log('Build process failed: ' + e.message);
	}
}	

/*
 * Tasks
 */
 
 function css() {
	var postcss = require('postcss');
	
	var input = fs.readFileSync('src/style.css', 'utf8');

	postcss([
		require('postcss-inline-comment')(),
		require('postcss-import')({
			path: 'src'}),
		require('postcss-custom-properties')(),
		require('postcss-calc')({
			preserve: false,
			precision: 5
		}),
		require('autoprefixer-core')()
	])
	.process(input, { 
		//from: 'src/app.css', 
		//to: 'app.css' 
	})
	.then(function(result) {
		fs.writeFileSync('dist/style.css', result.css);
        //if ( result.map ) fs.writeFileSync('app.css.map', result.map);
    });
}

function copyToDist() {
	console.log('Task copyToDist...');
	
	fs.emptyDirSync('dist');
	
	fs.copySync('src/index.html', 'dist/index.html', {replace: true});
	fs.copySync('src/script.js', 'dist/script.js', {replace: true});
	fs.copySync(
		'C:/Dropbox/mgiulio/prjexs/block-ui/blockui.js', //'src/blockui.js', 
		'dist/blockui.js', 
		{replace: true}
	);
}
